# Generated by Django 5.2.4 on 2025-07-04 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testcentre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_applicants', models.PositiveIntegerField()),
                ('test_centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcentre.testcentre')),
            ],
        ),
    ]
