# Generated by Django 5.1.3 on 2025-07-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testslot',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='testslot',
            name='start_time',
        ),
        migrations.AddField(
            model_name='testslot',
            name='time_range',
            field=models.CharField(default='8:00 AM - 10:00 AM', max_length=100),
            preserve_default=False,
        ),
    ]
