# Generated by Django 5.2.4 on 2025-07-04 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpanel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=20)),
                ('pdl_number', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('country_of_residence', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('driving_school', models.CharField(max_length=100)),
                ('license_type', models.CharField(max_length=50)),
                ('document_upload', models.FileField(upload_to='documents/')),
                ('confirmed', models.BooleanField(default=False)),
                ('test_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.testslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
