# Generated by Django 5.2.4 on 2025-07-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='driving_school',
            field=models.CharField(choices=[('AA Kenya', 'AA Kenya'), ('Seniors Driving School', 'Seniors Driving School'), ('Leopard Driving School', 'Leopard Driving School'), ('Hillys Driving School', 'Hillys Driving School'), ('Iqra Driving School', 'Iqra Driving School'), ('Sony Driving School', 'Sony Driving School'), ('Wings Driving School', 'Wings Driving School'), ('Budget Driving School', 'Budget Driving School'), ('Heltz Driving School', 'Heltz Driving School'), ('Petanns Driving School', 'Petanns Driving School'), ('Rocky Driving School', 'Rocky Driving School'), ('Jitegemea Driving School', 'Jitegemea Driving School'), ('Glory Driving School', 'Glory Driving School'), ('Top Gear Driving School', 'Top Gear Driving School')], max_length=50),
        ),
    ]
