# Generated by Django 5.2.4 on 2025-07-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_driving_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='license_type',
            field=models.CharField(choices=[('Class A', 'Class A'), ('Class B', 'Class B'), ('Class C', 'Class C'), ('Class F', 'Class F'), ('CDL', 'CDL')], max_length=20),
        ),
    ]
