# Generated by Django 5.2.4 on 2025-07-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcentre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcentre',
            name='capacity',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
