# Generated by Django 5.2.3 on 2025-07-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcentre', '0002_testcentre_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcentre',
            name='location',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
